name: Java CI with SonarQube

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.2'

      - name: Build with Gradle
        run: gradle build

      - name: Run Tests with Gradle
        run: gradle test --info

      - name: Run SonarQube Scan
        run: gradle sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}